export const MANIFEST_REPO = "quick-start-manifest";
export const HLD_REPO = "quick-start-hld";
export const APP_REPO = "quick-start-app";
export const HELM_REPO = "quick-start-helm";
export const APP_REPO_LIFECYCLE = "quick-start-lifecycle";
export const APP_REPO_BUILD = "quick-start-app-build";
export const DIRECTORY_LIST: string[] = [MANIFEST_REPO, HLD_REPO, APP_REPO];
export const USER = "service_account";
export const WORKSPACE = "test-env";
